### ISSUE TITLE
Update platform input support to support addition of additional data sources (drugs)

### ISSUE THREAD

**Issue by JarrodBaker** [opentargets/platform#1173]
> Reminder: PIS should only be used to load data into the Opentargets eco-system, processing should take place in a subsequent step.

As a developer on Opentargets, I want a way to add new data sources / fields to be collected when PIS runs through configuration.

PIS current has a data configuration file `config.yaml` which is used to specify input sources, output directories, etc. This could be extended with something like 

```
drug: 
  datasource: ChEMBL
    type: elasticsearch
    url: ...
    port: ...
    indices:
      - index_1
        - field_1
        - ...
        - field_n
      - index_n  
```
`type` could later be extended to support other mediums, and when we want to update the fields gathered from the ChEMBL Elasticsearch the relevant index/field configuration would be updated.
