### ISSUE TITLE
API and Services refactoring maintenance for the next release

### ISSUE THREAD

**Issue by mkarmona** [opentargets/platform#1580]
Things to upgrade

- API frameworks
- Clickhouse latest stable and jdbc client
- Elasticsearch to https://www.elastic.co/guide/en/elasticsearch/reference/7.12/release-notes-7.12.1.html so it can be usable with elastic4scala library

Things to mind when bumping to new versions

- check underlying jvm libraries are compatible like play framework, playjson, Jackson, elastic4s and ch client

**Comment by mkarmona** [comment]
this is an example of bumping [few packages](opentargets/genetics-api/pull/63)

**Comment by mkarmona** [comment]
aparently, the elasticsearch yml file needs to contain paths to logs and data configured otherwise it goes to the wrong place and not by default to debian anymore

```yaml
cluster.name: 493587c8-568f-490d-9eda-49dde0e13d09
network.host: 0.0.0.0
http.port: 9200
bootstrap.memory_lock: true
path.logs: /var/log/elasticsearch
path.data: /var/lib/elasticsearch
```
the same will happen with `log4j2.properties` configuration file as it needs to append at the end this and info gotten [from here](https://stackoverflow.com/questions/40908998/error-unable-to-locate-plugin-type-for-rollingfile-and-for-timebasedtriggeringp)
```
rootLogger.level = info
rootLogger.appenderRef.rolling.ref = rolling
```
