### ISSUE TITLE
Snapshot 18.12 failing

### ISSUE THREAD

**Issue by pieterlukasse** [opentargets/platform#387]
I am trying the following steps, but am not getting a snapshot in my ES (ES 5.6.10):

1) Register the repo to take the 18.12 snapshot from https://storage.googleapis.com/open-targets-data-releases :
 
```
curl -XPUT 'localhost:9200/_snapshot/ot_repo?verify=false&pretty' -H 'Content-Type: application/json' -d'
{
  "type": "url",
  "settings": {
	"url": "https://storage.googleapis.com/open-targets-data-releases/18.12/output/es_snapshot"
   }
}
'
```
(The snapshot is available, see https://console.cloud.google.com/storage/browser/open-targets-data-releases/18.12/output/es_snapshot ).

2) Get snapshot name with:

```
curl -i -H "Accept: application/json" http://localhost:9200/_snapshot/ot_repo/_all?pretty
```
This returns an empty list:

```
HTTP/1.1 200 OK
content-type: application/json; charset=UTF-8
content-length: 24

{
  "snapshots" : [ ]
}
```

**Comment by pieterlukasse** [comment]
I also tried with ES 5.6.14, same result.

**Comment by mkarmona** [comment]
@pieterlukasse few things to double check with your es5 configuration as es5 has basically two ways of loading a snapshot for GCS.

1. If you are using public urls as `https://console.cloud.google.com/storage/...`then your elasticsearch configuration must contain this line `repositories.url.allowed_urls: ["https://s3-eu-west-1.amazonaws.com/*","https://storage.googleapis.com/*"]`
2. or in the case you are using google buckets directly you will be using the elasticsearch extension `elasticsearch-plugin install repository-gcs` and then you can directly specify the google bucket in your es repository configuration and you have to `PUT` this as `localhost:9200/_snapshot/foobar`

```json
{
  "type": "gcs",
  "settings": {
    "bucket": "open-targets-data-releases",
    "base_path": "18.12/output/es_snapshot/",
    "max_restore_bytes_per_sec": "1000mb",
    "max_snapshot_bytes_per_sec": "1000mb"
  }
}
```
Which way are you using? and, are you meeting the requirements for allowing public urls being used by elasticsearch as it is shown by the point 1? I would recomend you to use [this tool](https://www.elastic.co/guide/en/elasticsearch/client/curator/current/installation.html) and here a configuration example
```
cat <<EOF > curator_restore.yaml
actions:
  1:
    action: restore
    description: Restore my_index from my_snapshot in my_repository
    options:
      repository: 'foobar'
      name:
      indices:
      extra_settings:
        index_settings:
          number_of_replicas: 0
      include_global_state: False
      wait_for_completion: true
      max_wait: 3600
      wait_interval: 10
    filters:
    - filtertype: state
      state: SUCCESS
      exclude:
    - filtertype: pattern
      kind: prefix
      value: 'curator-'
EOF
```
