### ISSUE TITLE
Roadmap: Configuration of data type and data source

### ISSUE THREAD

**Issue by mkarmona** [opentargets/platform#581]
I would expecting something like this
```yaml
evidences:
  default:
    schema: <uri/file>
  datatypes:
    datatype1:
      schema: <uri/file>
      datasource1:
```
